### ISSUE TITLE
--since default value is unintuitive

### ISSUE THREAD

**Issue by stephenmathieson** [segmentio/cwlogs#4]
It's taking several minutes to get any logs back. This makes the tool pretty unusable, as I can stumble around the CloudWatch's clunky UI more quickly than that.

```
∴ time aws-vault exec prod -- cwlogs fetch integration-drip-v1
^C
real	2m24.997s
user	0m8.905s
sys	0m0.771s
```

Is there anything we can do to improve performance here?

**Comment by dfuentes** [comment]
The command you posted tries to fetch all logs ever produced by that service.  The most effective ways to speed up the search are:
1) Search for logs for a specific task (you can see the list with `cwlogs list integration-drip-v1`, then search for a specific task using `cwlogs fetch integration-drip-v1 -t <task id>`
2) Search for a smaller time window using `--since/--until` (for example, `cwlogs fetch integration-drip-v1 --since 1h` for the last hour of logs)

Besides narrowing your search, there's not a whole lot we can do, its just the speed of the AWS API's.

**Comment by stephenmathieson** [comment]
After posting this, I remembered I [wrote a node version of this awhile back](https://github.com/segmentio/node-cloudwatch-log-stream). It does not have the same performance problems and requires no additional configuration. Just do `--group integration-drip-v1` and it'll output what you expect.

If we're going to be migrating away from our (Segment's) default tooling for reading logs, IMO, we shouldn't make it any more complicated than what we had previously. Is there any way we can make the default behavior here a little more user-friendly?

**Comment by dfuentes** [comment]
I disagree that the linked version's use of hardcoded time windows is better.  It may output what you expect, but doesn't output what I would expect.

I agree that setting a default start time would be useful, but could be a bit misleading if logs you are looking for are outside of the default window.  It's also doesn't work well for the case where you want to dump all logs for a given task run (which is an operation that the warehouses team does often).  I'm open to a PR to set a default start time, I think we'd have to make it obvious what the default window is some way.

A workaround for you right now would be to set `--since` in your alias so you don't have to type it each time, and that is the behavior that works best for you.  You're also free to use whatever tool you'd like, if your node version works better for you, then there is no reason not to use it.

**Comment by tejasmanohar** [comment]
I agree with @stephenmathieson that it's rare that you want to get logs from the beginning of time. I also think it's rare that you want to see logs from exactly 1 hour ago though.

Maybe we should make `--since` required or at least, provide a warning if you don't supply `--since`?

**Comment by dfuentes** [comment]
Alright, I've made two changes which should help out with the issues raised here:

1. Before, the tool would try to grab all the events before outputting.  This made larger queries harder to distinguish between not working and just taking a long time.  https://github.com/segmentio/cwlogs/pull/8 changes it so that events are streamed immediately to the output as we receive them, and will warn you to try a smaller time window if events start to take longer to load (because of aws-sdk-go's exponential backoff).

2. I added a default value of 1h to since.  You can still specify "all", for instance if you want to grab all the logs for a given task.

I think that these two changes together make the tool feel more responsive, and give you better feedback when things aren't working well.

**Comment by stephenmathieson** [comment]
Awesome, thanks @dfuentes!
